//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAGUSA.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class CovidVaccineRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CovidVaccineRecord()
        {
            this.PersonalInformation = new HashSet<PersonalInformation>();
        }
    
        public int id { get; set; }
        public string firstDoseCovidVaccine { get; set; }
        public Nullable<System.DateTime> firstDoseDate { get; set; }
        public string SecondDoseCovidVaccine { get; set; }
        public Nullable<System.DateTime> secondDoseDate { get; set; }
        public string otherFirstDoseCovidVaccine { get; set; }
        public Nullable<System.DateTime> otherFirstDoseDate { get; set; }
        public string otherSecondDoseCovidVaccine { get; set; }
        public Nullable<System.DateTime> otherSecondDoseDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalInformation> PersonalInformation { get; set; }
    }
}
