//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAGUSA.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class CovidVaccineRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CovidVaccineRecord()
        {
            this.PersonalInformation = new HashSet<PersonalInformation>();
        }
    
        public int id { get; set; }
        public string firstDoseCovidVaccine { get; set; }
        public Nullable<System.DateTime> firstDoseDate { get; set; }
        public string SecondDoseCovidVaccine { get; set; }
        public Nullable<System.DateTime> secondDoseDate { get; set; }
        public string otherFirstDoseCovidVaccine { get; set; }
        public Nullable<System.DateTime> otherFirstDoseDate { get; set; }
        public string otherSecondDoseCovidVaccine { get; set; }
        public Nullable<System.DateTime> otherSecondDoseDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalInformation> PersonalInformation { get; set; }
    }
}
