//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAGUSA.ENTITY
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MedicalDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalDetails()
        {
            this.PersonalInformation = new HashSet<PersonalInformation>();
        }

        public int id { get; set; }
        [Required(ErrorMessage = "This value is required")]
        public string bloodGroup { get; set; }
        public Nullable<bool> bloodtransfusion { get; set; }
        public bool medicalClearance { get; set; }
        public bool allergies { get; set; }
        public string allergiesList { get; set; }
        public string medicalConditionsList { get; set; }
        public string regularMedications { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalInformation> PersonalInformation { get; set; }
    }
}
