//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAGUSA.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalDetails()
        {
            this.PersonalInformation = new HashSet<PersonalInformation>();
        }

        public int id { get; set; }
        public string bloodGroup { get; set; }
        public Nullable<bool> bloodtransfusion { get; set; }
        public bool medicalClearance { get; set; }
        public bool allergies { get; set; }
        public string allergiesList { get; set; }
        public string medicalConditionsList { get; set; }
        public string regularMedications { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalInformation> PersonalInformation { get; set; }
    }
}
