//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAGUSA.ENTITY
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PersonalInformation
    {
        public int id { get; set; }
        [Required(ErrorMessage = "This value is required")]
        public string firstName { get; set; }
        [Required(ErrorMessage = "This value is required")]
        public string lastName { get; set; }
        [Required(ErrorMessage = "This value is required")]
        public string addressCountry { get; set; }
        public string addressUS { get; set; }
        [Required(ErrorMessage = "This value is required")]
        public string mobilePhone { get; set; }
        public string whatsapp { get; set; }
        public int genderFk { get; set; }
        [Required(ErrorMessage = "This value is required")]
        public System.DateTime dateBirth { get; set; }
        [Required(ErrorMessage = "This value is required")]
        public string countryNationality { get; set; }
        [Required(ErrorMessage = "This value is required")]
        public string PassportNumber { get; set; }
        [Required(ErrorMessage = "This value is required")]
        public string visaNumberType { get; set; }
        public int emergencyContactCountryFk { get; set; }
        public int emergencyContactUSFk { get; set; }
        public int medicalDetailsFK { get; set; }

        public Nullable<int> covidVaccineFK { get; set; }
        public Nullable<System.DateTime> recordDate { get; set; }

        public virtual EmergencyContact EmergencyContact { get; set; }
        public virtual EmergencyContactUS EmergencyContactUS { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual MedicalDetails MedicalDetails { get; set; }
        public virtual CovidVaccineRecord CovidVaccineRecord { get; set; }
    }
}
